version: "3.9"

services:
  otel-collector:
    container_name: otel-collector
    platform: linux/amd64
    image: otel/opentelemetry-collector:latest
    command: ["--config=/conf/collector-config.yml"]
    volumes:
      - ./collector-config.yml:/conf/collector-config.yml
    ports:
      - "14268:14268"
  
  db:
    container_name: timescaledb
    image: timescale/timescaledb-ha:pg14-latest
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_USER}
      POSTGRES_USER: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432/tcp

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    ports:
      - 9090:9090/tcp
    volumes:
      - ${PWD}/prometheus.yml:/etc/prometheus/prometheus.yml

  promscale:
    container_name: promscale
    image: timescale/promscale:latest
    restart: on-failure
    environment:
      PROMSCALE_DB_CONNECT_RETRIES: 10
      PROMSCALE_WEB_TELEMETRY_PATH: /metrics-text
      PROMSCALE_DB_URI: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/postgres?sslmode=allow
      PROMSCALE_ENABLE_FEATURE: tracing
      PROMSCALE_OTLP_GRPC_SERVER_LISTEN_ADDRESS: ":9202"
      PROMSCALE_TELEMETRY_TRACE_JAEGER_ENDPOINT: "http://otel-collector:14268/api/traces"
    ports:
      - 9201:9201/tcp
      - 9202:9202/tcp
    depends_on:
      - db
      - prometheus

  grafana:
    container_name: grafana
    image: grafana/grafana
    environment:
      GF_INSTALL_PLUGINS: grafana-clock-panel,grafana-simple-json-datasource
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    depends_on:
      - jaeger-query
      - promscale
      - prometheus

  jaeger-query:
    container_name: jaeger
    image: 'jaegertracing/jaeger-query:1.30.0'
    command: ["--grpc-storage.server=promscale:9202"]
    restart: on-failure
    ports:
      - '16686:16686'
    environment:
      - SPAN_STORAGE_TYPE=grpc-plugin
    depends_on:
      - promscale