global:
  scrape_interval: 15s
scrape_configs:
  - job_name: "graphql-metrics"
    static_configs:
      # Mac
      - targets: ["docker.for.mac.host.internal:9464"]
      # Linux/Windows
      # - targets:["localhost":9464"]
remote_write:
  - url: "http://promscale:9201/write"
    remote_timeout: 30s
    queue_config:
      capacity: 10000
      max_samples_per_send: 3000
      batch_send_deadline: 10s
      min_shards: 4
      max_shards: 200
      min_backoff: 100ms
      max_backoff: 10s
remote_read:
  - url: "http://promscale:9201/read"
    read_recent: true