apiVersion: 1

deleteDatasources:
  - name: Jaeger
    orgId: 1
  - name: Promscale
    orgId: 1

datasources:
  - name: Jaeger
    type: jaeger
    access: proxy
    orgId: 1
    url: http://jaeger:16686
    basicAuth: false
    version: 1
    editable: true
  
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://promscale:9201
    basicAuth: false
    version: 1
    editable: true